### ISSUE TITLE
Error with version 4.26

### ISSUE THREAD

**Issue by binouze** [adjust/unity_sdk#207]
Hi, after updating plugin from 4.23.2 to 4.26.0 I have the following error:

Assets\Adjust\Android\AdjustAndroid.cs(472,50): error CS0121: The call is ambiguous between the following methods or properties: 'AndroidJavaObject.AndroidJavaObject(string, string[])' and 'AndroidJavaObject.AndroidJavaObject(string, AndroidJavaClass[])'

Unity 2020.1.17f1 - Platform Android
Windows 10

**Comment by uerceg** [comment]
Hi @binouze 

Thanks for reporting this. Nothing which popped up on our end so far. Will give your exact Unity version a shot and keep you posted on the issue.

**Comment by gtino** [comment]
Same problem on Unity 2019.4.19f1 

`Assets/Externals/Adjust/Android/AdjustAndroid.cs(472,50): error CS0121: The call is ambiguous between the following methods or properties: 'AndroidJavaObject.AndroidJavaObject(string, string[])' and 'AndroidJavaObject.AndroidJavaObject(string, AndroidJavaClass[])'`

**Comment by uerceg** [comment]
Hi @gtino 

Which operating system you're running Unity IDE on?

**Comment by gtino** [comment]
Mac OSX Mojave

**Comment by uerceg** [comment]
Thanks for the additional info. I'm actually failing for now to reproduce this, but will keep you posted.

**Comment by uerceg** [comment]
Actually managed to reproduce it in @binouze's setup from this [comment](https://github.com/adjust/unity_sdk/issues/207#issue-806395049). We're on it.

**Comment by uerceg** [comment]
@binouze @gtino Here's patch SDK update which we plan to release. Before doing that, if you guys wanna give it a shot and let us know if it fixed your issue, would be great.


[Adjust_v4.26.1.unitypackage.zip](https://github.com/adjust/unity_sdk/files/5967080/Adjust_v4.26.1.unitypackage.zip)

**Comment by binouze** [comment]
@uerceg thanks, I'll try this tomorrow morning and keep you informed

**Comment by gtino** [comment]
Trying it right now - I'll let you know ASAP

**Comment by gtino** [comment]
It compiles locally, so I guess the issue has been fixed - I will soon launch the CI build and I will let you know if I don't have problems anymore there either.

**Comment by uerceg** [comment]
Great, thanks! Let us know if CI build went well when you get a chance.

**Comment by gtino** [comment]
Everything seems to be ok on our side now [ the fix was exactly what I was expecting so everything looks good.

**Comment by uerceg** [comment]
Amazing, thank you so much for help on this topic. 🍺 We have just released [v4.26.1](https://github.com/adjust/unity_sdk/releases/tag/v4.26.1) with this fix.

Error being reported is pretty self explanatory - `AndroidJavaObject` seems to have two overloaded implementations and us passing `null` in error line seems to be confusing Unity since it has no idea if we want to invoke `AndroidJavaObject.AndroidJavaObject(string, string[])` or `AndroidJavaObject.AndroidJavaObject(string, AndroidJavaClass[])`. Fix is pretty trivial - instead of passing `null`, we just initialised `string[]` array with `null` and passed that variable and now it works.

What we found interesting is that for exactly identical Unity IDE versions in OSX and Windows we managed to reproduce issue in Windows (like @binouze reported) while in OSX no error was reported. Also we tried several different Unity IDE versions (ranging from 2017 until 2020) and saw this error nowhere. Not sure at this moment what might be the reason for this inconsistent behaviour.

In case issue still persists or you maybe have more questions regarding this issue, feel free to comment/reopen.

Cheers
